version: 1
groups:
  - annotation: ckanext-json-viewer
    options:
      - key: ckanext.json_viewer.default_theme
        description: Default theme for preview
        default: default-light
        editable: true

      - key: ckanext.json_viewer.default_view_name
        description: Default view name
        default: JSON Viewer
        editable: true

      - key: ckanext.json_viewer.default_description
        description: Default description
        default: ""
        editable: true
